2024-08-26 19:33:24 align.main INFO : Reading netlist: /home/adair/Documents/CAD/characterization_script_sandbox_rundir/cm_ota/cm_ota.sp subckt=CM_OTA, flat=0
2024-08-26 19:33:24 align.compiler.compiler INFO : Starting topology identification...
2024-08-26 19:33:24 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/cmdline.py", line 197, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/main.py", line 167, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/compiler/compiler.py", line 76, in compiler_input
    ckt_parser.parse(lines)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/schema/parser.py", line 88, in parse
    self._dispatch(cache)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/schema/parser.py", line 106, in _dispatch
    self._process_instance(token.value.upper(), args, kwargs)
  File "/home/adair/Documents/CAD/venv/lib/python3.10/site-packages/align/schema/parser.py", line 161, in _process_instance
    assert len(args) == len(model.pins), \
AssertionError: Model SKY130_FD_PR__PFET_01V8 has 4 pins ['D', 'G', 'S', 'B']. 10 nets ['NET1', 'INN', 'ITAIL', 'AVSS', 'SKY130_FD_PR__NFET_01V8', 'XM3', 'NET1', 'NET1', 'AVDD_1V8', 'AVDD_1V8'] were passed when instantiating XM1.
